require("core.options")
require("core.keymaps")
require("core.autocmds")

require("plugins.git")
require("plugins.indent")
require("plugins.oil")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.telescope")
require("plugins.lualine")
